name = "vvip-web"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
routes = [
  { pattern = "inconigto.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.inconigto.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.inconigto.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.inconigto.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.inconigto.web.id", custom_domain = true },
  { pattern = "support.zoom.us.inconigto.web.id", custom_domain = true },  
  { pattern = "uts-front.line-apps.com.inconigto.web.id", custom_domain = true },
  { pattern = "stickershop.line.me.inconigto.web.id", custom_domain = true },
  { pattern = "i-integration-gojekapi.com.inconigto.web.id", custom_domain = true },
  { pattern = "gopay-raccoon.gojekapi.com.inconigto.web.id", custom_domain = true },
  { pattern = "media-cgk1-1.cdn.whatsapp.net.inconigto.web.id", custom_domain = true },
  { pattern = "sentry-uit.line-apps.com.inconigto.web.id", custom_domain = true },
  { pattern = "api.midtrans.com.inconigto.web.id", custom_domain = true },
  { pattern = "ads.ruangguru.com.inconigto.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.inconigto.web.id", custom_domain = true }
]
[vars]
